### PR TITLE
Support mosh

### PR DESCRIPTION
**Pull request by daleione**

### CODE REVIEW

**Comment by jpalardy** [comment]
Hi there,

This is quite a diff… let me try to think if there's a more general way of doing this. Maybe the logic to determine what `cmd` to use could be somewhere else (external).

**Comment by jpalardy** [comment]
I've been thinking about this.

How about:
- if there is only 1 column
  - use `$SSH`, treat both port/no-port cases
- if there are 2 columns
  - use column 1 as `$SSH` and column 2 as case above ^

Questions:
- how to handle more than 2 columns? (related to next item)
  - maybe the logic is: if > 1 column, use as-is. That would cover 2 columns and beyond.
- allow for "comments"? … throw away everything after `#`?

We are also reaching the point where all this logic might deserve a separate function.

Thoughts?

**Comment by daleione** [comment]
You try the commit locally, all you mentioned are supported.
Maybe the most worse thing is that the code need more comments.
Now, It support
1. one column
2. one column with port or # 
3. two columns and $1 is the mosh
4. two columns with port or #

**Comment by jpalardy** [comment]
Have a look at #9

**Pull request closed without merging**
